create  DATABASE hosp_project;

--  1. List all patients’ first name, last name, and gender.

SELECT 
    first_name, last_name, gender
FROM
    hosp_project.patients;

--  2. Retrieve all doctors who specialize in “Pediatrics”.

SELECT 
    *
FROM
    hosp_project.doctors
WHERE
    specialization = 'Pediatrics';

--  3. Count the total number of appointments for each doctor.

SELECT 
    doctor_id, COUNT(appointment_id)
FROM
    hosp_project.appointments
GROUP BY 
	doctor_id
ORDER BY 
	doctor_id ASC;
    
-- 4. List all appointments scheduled for today.

SELECT 
    appointment_id, appointment_date
FROM
    hosp_project.appointments
WHERE
    appointment_date = '2023-01-01';
    
-- 5. Show the total billing amount for each patient.

SELECT 
    patient_id, amount
FROM
    hosp_project.billing;
    
-- 6. Find the total number of treatments per treatment type and show only types with more than 40 treatments.

SELECT 
    treatment_type, COUNT(treatment_type) AS Count
FROM
    hosp_project.treatments
GROUP BY 
	treatment_type
HAVING 
	Count >= '40'
ORDER BY 
	Count ASC;

-- 7. List each doctor name along with the number of appointments they have had in Jan.

SELECT 
    d.first_name,
    COUNT(appointment_id) AS total_appointments
FROM
    hosp_project.appointments a
        JOIN
    hosp_project.doctors d 
ON 
	a.doctor_id = d.doctor_id
WHERE
    appointment_date LIKE '2023-01-%'
GROUP BY 
	d.first_name
ORDER BY 
	total_appointments ASC;
    
-- 8 Retrieve patients who have pending payments along with their bill amount and treatment type.

SELECT 
    b.patient_id,
    b.treatment_id,
    b.payment_status,
    t.treatment_type,
    t.cost
FROM
    hosp_project.billing b
        JOIN
    hosp_project.treatments t ON b.treatment_id = t.treatment_id
WHERE
    b.payment_status = 'Pending'
ORDER BY t.cost;


-- 9. Find the top 3 most expensive treatments.

SELECT *
FROM (
    SELECT 
        treatment_type, 
        round(AVG(cost),0) AS avg_cost
    FROM 
        hosp_project.treatments
    GROUP BY 
        treatment_type
) AS avg_costs
ORDER BY 
    avg_cost DESC
LIMIT 3;

-- Show the number of appointments per month for January, February, and March 2023.

SELECT 'January' AS month, COUNT(*) AS total_appointments
FROM hosp_project.appointments
WHERE appointment_date LIKE '2023-01-__'

UNION ALL
SELECT 'February', COUNT(*)
FROM hosp_project.appointments
WHERE appointment_date LIKE '2023-02-__'

UNION ALL
SELECT 'March', COUNT(*)
FROM hosp_project.appointments
WHERE appointment_date LIKE '2023-03-__';

-- 11 List the top 5 doctors with the highest number of completed appointments.

SELECT 
    d.first_name, COUNT(*) AS Count
FROM
    hosp_project.appointments AS a
        JOIN
    hosp_project.doctors AS d ON a.doctor_id = d.doctor_id
WHERE
    a.status = 'Completed'
GROUP BY d.first_name
ORDER BY Count DESC
LIMIT 5;

-- 12 Find patients who have never had a treatment costing more than 50,000.

SELECT * from ( select
    p.first_name, SUM(b.amount) AS total_amount
FROM
    hosp_project.billing AS b
        JOIN
    hosp_project.patients AS p ON b.patient_id = p.patient_id
    group by p.first_name) as patient_totals
    where total_amount <= 50000
    order by total_amount asc;
    
-- 13. Show the total billing amount generated by each doctor by joining the doctors, appointments, treatments, and billing tables.

SELECT 
    d.first_name,
    ROUND((SUM(b.amount)),0) AS total_billing
FROM 
    hosp_project.doctors AS d
JOIN 
    hosp_project.appointments AS a 
    ON d.doctor_id = a.doctor_id
JOIN 
    hosp_project.treatments AS t 
    ON a.appointment_id = t.appointment_id
JOIN 
    hosp_project.billing AS b 
    ON t.treatment_id = b.treatment_id
GROUP BY 
    d.doctor_id, d.first_name, d.last_name
ORDER BY 
    total_billing DESC;

-- 14. Rank patients by the total amount they have paid and show the top 10 highest paying patients.

SELECT 
    *
FROM
    (SELECT 
        p.first_name, 
        ROUND(SUM(b.amount),0) AS total_amount,
        RANK() OVER (ORDER BY SUM(b.amount) DESC) AS ranking
    FROM
        hosp_project.billing AS b
    JOIN 
        hosp_project.patients AS p 
        ON b.patient_id = p.patient_id
    GROUP BY 
        p.first_name) AS patient_totals
ORDER BY 
    total_amount DESC
LIMIT 10;

-- 15. Calculate the average treatment cost per month for the current year and display trends month-wise.

SELECT 
    MONTH(a.appointment_date) AS month_number,
    MONTHNAME(a.appointment_date) AS month_name,
    ROUND(AVG(t.cost), 0) AS avg_treatment_cost
FROM 
    hosp_project.appointments AS a
JOIN 
    hosp_project.treatments AS t
    ON a.appointment_id = t.appointment_id
WHERE 
    YEAR(a.appointment_date) = 2023
GROUP BY 
    month_number, month_name
ORDER BY 
    month_number;
